services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: chromatik-backend
    ports:
      - "5000:5000"
    environment:
      JWT_SECRET: "your_jwt_secret"
      NODE_ENV: "development"
      MONGO_URI: "mongodb://mongo:27017/chromatik"
      PORT: 5000
    volumes:
      - ./backend:/app
    command: ["npx", "tsc-watch", "--onSuccess", "node ./dist/index.js"]
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: chromatik-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "serve"]
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: chromatik-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
