FROM node:18

WORKDIR /app

# package.json ve package-lock.json’u ayrı ayrı kopyala
COPY package.json package-lock.json ./

# Dependencies’i yükle (postinstall tetiklenmez)
RUN npm install --legacy-peer-deps --ignore-scripts

# TypeScript, ts-node, nodemon global
RUN npm install -g typescript ts-node nodemon

# Tüm kaynak dosyaları kopyala
COPY . .

# Hot-reload
CMD ["nodemon", "--watch", "src", "--ext", "ts,js,json", "--exec", "ts-node", "src/index.ts"]
